theme = "tokyonight_storm"

[keys.normal]
G = "goto_file_end"
X = "extend_line_above"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "info"


[editor.file-picker]
# disable filter hidden files (dotfiles)
hidden = false
# read git-ignored files
git-ignore = false
